### ISSUE TITLE
java.lang.VerifyError when deriving Applicative for object superclass

### ISSUE THREAD

**Issue by lmmworkv** [typelevel/shapeless-contrib#26]
Up at http://scastie.org/7477 :

```
/***
scalaVersion := "2.11.2"

libraryDependencies += "org.typelevel" %% "shapeless-scalaz" % "0.3"
*/
import scalaz._
import scalaz.Scalaz._
import shapeless.contrib.scalaz._

abstract class Mangler[F[_]: Applicative]
case class Count(value: Int)

object CountMangler extends Mangler[({type L[A] = Writer[Count, A]})#L]

object Main extends App {
  CountMangler
}
```

Running this gets:

```
java.lang.VerifyError: (class: CountMangler$, method: <init> signature: ()V) Expecting to find object/array on stack
at Main$.delayedEndpoint$Main$1(test.scala:16)
at Main$delayedInit$body.apply(test.scala:15)
```

I discovered this error on scala 2.10.4 / shapeless-scalaz 0.2, which gave a slightly different message:

```
java.lang.VerifyError: Bad type on operand stack
Exception Details:
Location:
  CountMangler$.<init>()V @17: invokespecial
Reason:
  Type uninitializedThis (current frame, stack[2]) is not assignable to 'CountMangler$'
Current Frame:
  bci: @17
  flags: { flagThisUninit }
  locals: { uninitializedThis, 'scala/runtime/VolatileObjectRef' }
  stack: { uninitializedThis, 'scalaz/WriterT$', uninitializedThis, 'scala/runtime/VolatileObjectRef' }
Bytecode:
  0000000: 2ab2 002c bb00 1159 0157 01b7 002f 4c2a
  0000010: 2bb7 0031 b600 35b6 0039 b700 3c2a b300
  0000020: 3eb1                                   

    at MyTest.doesntExplode(MyTest.scala:10)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
    at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
    at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
```

**Comment by ehx-v1** [comment]
So it's because of things happening prior to the super constructor call?
Asking because I have similar problems in a totally different environment. (No, not Powermock. JavaFX and complex custom code.)
